import base64
import struct
import logging
from pathlib import Path
from config import config

def encode_varint(value: int) -> bytes:
    if value < 64:
        return bytes([value])
    elif value < 16384:
        return struct.pack('>H', 0x4000 | value)
    elif value < 1073741824:
        return struct.pack('>I', 0x80000000 | value)
    else:
        return struct.pack('>Q', 0xC000000000000000 | value)

def encode_tlv(tag: int, value_buf: bytes) -> bytes:
    tag_buf = encode_varint(tag)
    len_buf = encode_varint(len(value_buf))
    return tag_buf + len_buf + value_buf

def encode_string_field(tag: int, val: str) -> bytes:
    return encode_tlv(tag, val.encode('utf-8'))

def encode_bool_field(tag: int, val: bool) -> bytes:
    return encode_tlv(tag, bytes([0x01 if val else 0x00]))

def encode_varint_field(tag: int, val: int) -> bytes:
    return encode_tlv(tag, encode_varint(val))

def encode_string_array_field(tag: int, string_array: list[str]) -> bytes:
    bufs = []
    for s in string_array:
        str_buf = s.encode('utf-8')
        bufs.append(encode_varint(len(str_buf)))
        bufs.append(str_buf)
    return encode_tlv(tag, b''.join(bufs))

def base64url(buffer: bytes) -> str:
    return base64.urlsafe_b64encode(buffer).decode('ascii').rstrip('=')

cached_der_buffer = None

def get_der_certificate() -> bytes:
    global cached_der_buffer
    if cached_der_buffer is not None:
        return cached_der_buffer
    paths = [
        "/opt/trusttunnel/certs/cert.pem",
        Path(__file__).parent / "certs" / "cert.pem"
    ]
    for p in paths:
        if Path(p).exists():
            try:
                pem = Path(p).read_text(encoding='utf-8')
                base64_data = pem.replace('-----BEGIN CERTIFICATE-----', '').replace('-----END CERTIFICATE-----', '').replace('\n', '').replace('\r', '').strip()
                cached_der_buffer = base64.b64decode(base64_data)
                return cached_der_buffer
            except Exception as e:
                logging.error(f"Error parsing cert {p}: {e}")
    return None

def generate_tt_link(username: str, password: str, notes: str = "") -> str:
    host = config.TT_HOST or config.DOMAIN or "localhost"
    port = config.TT_PORT
    address = f"{host}:{port}"
    
    chunks = []
    # Tag 0x00: version 1
    chunks.append(encode_varint_field(0x00, 1))
    # Tag 0x01: hostname
    chunks.append(encode_string_field(0x01, host))
    # Tag 0x02: addresses
    chunks.append(encode_string_field(0x02, address))
    # Tag 0x05: username
    chunks.append(encode_string_field(0x05, username))
    # Tag 0x06: password
    chunks.append(encode_string_field(0x06, password))
    
    # Tag 0x07: skip_verification
    if config.TT_SKIP_VERIFY:
        chunks.append(encode_bool_field(0x07, True))
        
    # Tag 0x08: certificate
    der_buffer = get_der_certificate()
    if der_buffer:
        chunks.append(encode_tlv(0x08, der_buffer))
        
    # Tag 0x0c: name
    display_name = f"{username} ({notes})" if notes else username
    chunks.append(encode_string_field(0x0c, display_name))
    
    # Tag 0x03: custom_sni
    if config.TT_CUSTOM_SNI:
        chunks.append(encode_string_field(0x03, config.TT_CUSTOM_SNI))
        
    # Tag 0x0d: dns_upstreams
    chunks.append(encode_string_array_field(0x0d, ["1.1.1.1", "8.8.8.8"]))
    
    payload_buf = b''.join(chunks)
    encoded_payload = base64url(payload_buf)
    return f"tt://?{encoded_payload}"

def sync_tt_credentials(users: list):
    credentials_path = Path(config.TT_CREDENTIALS_PATH)
    if not credentials_path.parent.exists():
        # TT is likely not installed or path is wrong
        return False
        
    lines = ["# Generated by NaiveProxy Panel for TrustTunnel", ""]
    active_users = [u for u in users if u.get("enabled", True)]
    
    if not active_users:
        lines.append("client = []")
    else:
        for u in active_users:
            uname = u.get("login", "").replace('"', '\\"')
            pwd = u.get("password", "").replace('"', '\\"')
            lines.append("[[client]]")
            lines.append(f'username = "{uname}"')
            lines.append(f'password = "{pwd}"')
            lines.append("")
            
    try:
        credentials_path.write_text("\n".join(lines), encoding="utf-8")
        
        # Trigger restart
        import subprocess
        subprocess.Popen(["systemctl", "reload", "trusttunnel"])
        return True
    except Exception as e:
        logging.error(f"Failed to sync TT credentials: {e}")
        return False
