const express = require('express');
const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');
const crypto = require('crypto');

const app = express();
const PORT = process.env.PORT || 3000;
const DB_PATH = path.join(__dirname, 'db.json');

app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// ==========================================
// DB Helper Functions
// ==========================================
function readDB() {
  try {
    if (!fs.existsSync(DB_PATH)) {
      // Re-create if missing
      const defaults = {
        settings: {
          serverHost: "yourserver.com",
          serverPort: 8443,
          vpnTomlPath: "/opt/trusttunnel/vpn.toml",
          credentialsTomlPath: "./credentials.toml",
          restartCommand: "sudo systemctl restart trusttunnel",
          customSni: "",
          skipVerification: false,
          dnsUpstreams: ["1.1.1.1", "8.8.8.8"]
        },
        users: []
      };
      fs.writeFileSync(DB_PATH, JSON.stringify(defaults, null, 2));
      return defaults;
    }
    const data = fs.readFileSync(DB_PATH, 'utf-8');
    return JSON.parse(data);
  } catch (err) {
    console.error('Error reading db.json:', err);
    return { settings: {}, users: [] };
  }
}

function writeDB(data) {
  try {
    fs.writeFileSync(DB_PATH, JSON.stringify(data, null, 2));
    return true;
  } catch (err) {
    console.error('Error writing db.json:', err);
    return false;
  }
}

// ==========================================
// TOML Credential Sync Generator
// ==========================================
function syncCredentials(dbData) {
  const settings = dbData.settings;
  const filePath = path.resolve(settings.credentialsTomlPath || './credentials.toml');
  
  // Filter only enabled users
  const activeUsers = dbData.users.filter(u => u.enabled);
  
  let tomlContent = `# Generated by TrustTunnel Web Panel
# Active Credentials Count: ${activeUsers.length}
# Last Updated: ${new Date().toISOString()}

`;

  if (activeUsers.length === 0) {
    tomlContent += `client = []\n`;
  } else {
    activeUsers.forEach(user => {
      // Escape quotes to prevent TOML parsing errors
      const safeUser = user.username.replace(/"/g, '\\"');
      const safePass = user.password.replace(/"/g, '\\"');
      tomlContent += `[[client]]\nusername = "${safeUser}"\npassword = "${safePass}"\n\n`;
    });
  }

  try {
    const dir = path.dirname(filePath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(filePath, tomlContent, 'utf-8');
    console.log(`Successfully synchronized credentials to: ${filePath}`);
    return { success: true, filePath };
  } catch (err) {
    console.error(`Failed to write credentials TOML to ${filePath}:`, err);
    return { success: false, error: err.message };
  }
}

// ==========================================
// Service Restart Trigger
// ==========================================
function triggerRestart(settings, callback) {
  const cmd = settings.restartCommand;
  if (!cmd || cmd.trim() === "") {
    return callback(null, "No restart command configured. Changes saved locally.");
  }
  
  console.log(`Executing restart command: "${cmd}"`);
  exec(cmd, (error, stdout, stderr) => {
    if (error) {
      console.error(`Restart command failed: ${error.message}`);
      // Gracefully return error so it can be shown in settings / logs
      return callback(error, stdout || stderr || error.message);
    }
    console.log(`Restart command succeeded!`);
    return callback(null, stdout || "Service restarted successfully.");
  });
}

// ==========================================
// RFC 9000 VarInt & TLV Deep-Link Encoder
// ==========================================
function encodeVarInt(value) {
  if (value < 64) {
    return Buffer.from([value]);
  } else if (value < 16384) {
    return Buffer.from([
      0x40 | (value >> 8),
      value & 0xFF
    ]);
  } else if (value < 1073741824) {
    return Buffer.from([
      0x80 | (value >> 24),
      (value >> 16) & 0xFF,
      (value >> 8) & 0xFF,
      value & 0xFF
    ]);
  } else {
    const buf = Buffer.alloc(8);
    buf.writeBigUInt64BE(BigInt(value));
    buf[0] |= 0xC0;
    return buf;
  }
}

function encodeTLV(tag, valueBuf) {
  const tagBuf = encodeVarInt(tag);
  const lenBuf = encodeVarInt(valueBuf.length);
  return Buffer.concat([tagBuf, lenBuf, valueBuf]);
}

function encodeStringField(tag, val) {
  return encodeTLV(tag, Buffer.from(val, 'utf-8'));
}

function encodeBoolField(tag, val) {
  return encodeTLV(tag, Buffer.from([val ? 0x01 : 0x00]));
}

function encodeVarIntField(tag, val) {
  return encodeTLV(tag, encodeVarInt(val));
}

function encodeStringArrayField(tag, stringArray) {
  const bufs = [];
  for (const str of stringArray) {
    const strBuf = Buffer.from(str, 'utf-8');
    bufs.push(encodeVarInt(strBuf.length));
    bufs.push(strBuf);
  }
  return encodeTLV(tag, Buffer.concat(bufs));
}

function base64url(buffer) {
  return buffer.toString('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=/g, '');
}

let cachedDerBuffer = null;
function getDerCertificate() {
  if (cachedDerBuffer) return cachedDerBuffer;
  try {
    const paths = [
      '/opt/trusttunnel/certs/cert.pem',
      path.join(__dirname, 'certs/cert.pem')
    ];
    
    let certPath = null;
    for (const p of paths) {
      if (fs.existsSync(p)) {
        certPath = p;
        break;
      }
    }
    
    if (!certPath) return null;
    
    const pem = fs.readFileSync(certPath, 'utf-8');
    const base64Data = pem
      .replace(/-----BEGIN CERTIFICATE-----/, '')
      .replace(/-----END CERTIFICATE-----/, '')
      .replace(/\s/g, '');
    cachedDerBuffer = Buffer.from(base64Data, 'base64');
    return cachedDerBuffer;
  } catch (err) {
    console.error('Error reading/parsing self-signed certificate:', err);
    return null;
  }
}

function generateDeepLink(user, settings) {
  const host = settings.serverHost || "yourserver.com";
  const port = parseInt(settings.serverPort) || 8443;
  const address = `${host}:${port}`;
  
  const chunks = [];
  
  // Tag 0x00: version (VarInt) - Version 1 matches DEEP_LINK.md status
  chunks.push(encodeVarIntField(0x00, 1));
  
  // Tag 0x01: hostname (String)
  chunks.push(encodeStringField(0x01, host));
  
  // Tag 0x02: addresses (String) - multiple possible, we push one
  chunks.push(encodeStringField(0x02, address));
  
  // Tag 0x05: username (String)
  chunks.push(encodeStringField(0x05, user.username));
  
  // Tag 0x06: password (String)
  chunks.push(encodeStringField(0x06, user.password));
  
  // Tag 0x07: skip_verification (Bool)
  if (settings.skipVerification) {
    chunks.push(encodeBoolField(0x07, true));
  }
  
  // Tag 0x08: certificate (Bytes) - Embed self-signed certificate so that the app trusts it automatically!
  const derBuffer = getDerCertificate();
  if (derBuffer) {
    chunks.push(encodeTLV(0x08, derBuffer));
  }
  
  // Tag 0x0c: name (String) - Server display name
  const displayName = user.notes ? `${user.username} (${user.notes})` : user.username;
  chunks.push(encodeStringField(0x0c, displayName));
  
  // Tag 0x03: custom_sni (String) - if set
  if (settings.customSni && settings.customSni.trim() !== "") {
    chunks.push(encodeStringField(0x03, settings.customSni.trim()));
  }
  
  // Tag 0x0d: dns_upstreams (String[]) - if set
  if (settings.dnsUpstreams && settings.dnsUpstreams.length > 0) {
    const validDns = settings.dnsUpstreams.filter(dns => dns && dns.trim() !== "");
    if (validDns.length > 0) {
      chunks.push(encodeStringArrayField(0x0d, validDns));
    }
  }
  
  const payloadBuf = Buffer.concat(chunks);
  const encodedPayload = base64url(payloadBuf);
  
  return `tt://?${encodedPayload}`;
}

// ==========================================
// Client TOML Config Exporter
// ==========================================
function generateClientTOML(user, settings) {
  const host = settings.serverHost || "yourserver.com";
  const port = parseInt(settings.serverPort) || 8443;
  const address = `${host}:${port}`;
  
  let toml = `# TrustTunnel Client Configuration
# User: ${user.username}
# Generated: ${new Date().toISOString()}

[client]
server_address = "${address}"
username = "${user.username}"
password = "${user.password}"
mode = "general"
skip_verification = ${settings.skipVerification ? 'true' : 'false'}
`;

  if (settings.customSni && settings.customSni.trim() !== "") {
    toml += `custom_sni = "${settings.customSni.trim()}"\n`;
  }
  
  toml += `\n[dns]\n`;
  if (settings.dnsUpstreams && settings.dnsUpstreams.length > 0) {
    const dnsList = settings.dnsUpstreams.filter(dns => dns && dns.trim() !== "").map(dns => `"${dns}"`).join(', ');
    toml += `upstreams = [${dnsList}]\n`;
  } else {
    toml += `upstreams = ["1.1.1.1", "8.8.8.8"]\n`;
  }
  
  return toml;
}

// ==========================================
// REST API Routes
// ==========================================

// 1. GET Settings
app.get('/api/settings', (req, res) => {
  const db = readDB();
  res.json(db.settings);
});

// 2. POST Settings
app.post('/api/settings', (req, res) => {
  const db = readDB();
  const newSettings = req.body;
  
  // Merge and validate settings
  db.settings = {
    ...db.settings,
    ...newSettings,
    serverPort: parseInt(newSettings.serverPort) || 8443,
    skipVerification: !!newSettings.skipVerification,
    dnsUpstreams: Array.isArray(newSettings.dnsUpstreams) ? newSettings.dnsUpstreams : ["1.1.1.1", "8.8.8.8"]
  };
  
  if (writeDB(db)) {
    // Re-sync TOML in case paths changed
    const syncRes = syncCredentials(db);
    res.json({ success: true, settings: db.settings, sync: syncRes });
  } else {
    res.status(500).json({ success: false, error: "Failed to write database settings." });
  }
});

// 3. GET Users
app.get('/api/users', (req, res) => {
  const db = readDB();
  // Return users with their deep links pre-generated for UI simplicity
  const usersWithLinks = db.users.map(u => ({
    ...u,
    deepLink: generateDeepLink(u, db.settings)
  }));
  res.json(usersWithLinks);
});

// 4. POST Create User
app.post('/api/users', (req, res) => {
  const db = readDB();
  const { username, password, notes } = req.body;
  
  if (!username || username.trim() === "") {
    return res.status(400).json({ success: false, error: "Username is required." });
  }
  
  const cleanUsername = username.trim();
  
  // Check uniqueness
  const exists = db.users.some(u => u.username.toLowerCase() === cleanUsername.toLowerCase());
  if (exists) {
    return res.status(400).json({ success: false, error: `User '${cleanUsername}' already exists.` });
  }
  
  // Generate robust random password if not supplied
  const finalPassword = (password && password.trim() !== "") 
    ? password.trim() 
    : crypto.randomBytes(12).toString('hex'); // 24 character secure hex string
    
  const newUser = {
    username: cleanUsername,
    password: finalPassword,
    notes: (notes || "").trim(),
    enabled: true,
    createdAt: new Date().toISOString()
  };
  
  db.users.push(newUser);
  
  if (writeDB(db)) {
    const syncRes = syncCredentials(db);
    if (!syncRes.success) {
      return res.status(500).json({ success: false, error: "Failed to sync credentials file: " + syncRes.error });
    }
    
    // Trigger restart asynchronously
    triggerRestart(db.settings, (err, output) => {
      res.json({
        success: true,
        user: { ...newUser, deepLink: generateDeepLink(newUser, db.settings) },
        restartStatus: err ? "failed" : "success",
        restartMessage: output
      });
    });
  } else {
    res.status(500).json({ success: false, error: "Failed to save user to database." });
  }
});

// 5. PUT Update User (Notes only)
app.put('/api/users/:username', (req, res) => {
  const db = readDB();
  const username = req.params.username;
  const { notes } = req.body;
  
  const userIdx = db.users.findIndex(u => u.username.toLowerCase() === username.toLowerCase());
  if (userIdx === -1) {
    return res.status(404).json({ success: false, error: "User not found." });
  }
  
  db.users[userIdx].notes = (notes || "").trim();
  
  if (writeDB(db)) {
    res.json({ success: true, user: db.users[userIdx] });
  } else {
    res.status(500).json({ success: false, error: "Failed to save updates to database." });
  }
});

// 6. POST Toggle User State (Enable/Disable)
app.post('/api/users/:username/toggle', (req, res) => {
  const db = readDB();
  const username = req.params.username;
  
  const userIdx = db.users.findIndex(u => u.username.toLowerCase() === username.toLowerCase());
  if (userIdx === -1) {
    return res.status(404).json({ success: false, error: "User not found." });
  }
  
  // Toggle the enabled status
  db.users[userIdx].enabled = !db.users[userIdx].enabled;
  
  if (writeDB(db)) {
    const syncRes = syncCredentials(db);
    if (!syncRes.success) {
      return res.status(500).json({ success: false, error: "Failed to sync credentials file: " + syncRes.error });
    }
    
    triggerRestart(db.settings, (err, output) => {
      res.json({
        success: true,
        user: db.users[userIdx],
        restartStatus: err ? "failed" : "success",
        restartMessage: output
      });
    });
  } else {
    res.status(500).json({ success: false, error: "Failed to update user state." });
  }
});

// 7. DELETE User
app.delete('/api/users/:username', (req, res) => {
  const db = readDB();
  const username = req.params.username;
  
  const initialCount = db.users.length;
  db.users = db.users.filter(u => u.username.toLowerCase() !== username.toLowerCase());
  
  if (db.users.length === initialCount) {
    return res.status(404).json({ success: false, error: "User not found." });
  }
  
  if (writeDB(db)) {
    const syncRes = syncCredentials(db);
    if (!syncRes.success) {
      return res.status(500).json({ success: false, error: "Failed to sync credentials file: " + syncRes.error });
    }
    
    triggerRestart(db.settings, (err, output) => {
      res.json({
        success: true,
        restartStatus: err ? "failed" : "success",
        restartMessage: output
      });
    });
  } else {
    res.status(500).json({ success: false, error: "Failed to delete user." });
  }
});

// 8. GET User Connection details & standard config files
app.get('/api/users/:username/config', (req, res) => {
  const db = readDB();
  const username = req.params.username;
  
  const user = db.users.find(u => u.username.toLowerCase() === username.toLowerCase());
  if (!user) {
    return res.status(404).json({ success: false, error: "User not found." });
  }
  
  const deepLink = generateDeepLink(user, db.settings);
  const clientConfig = generateClientTOML(user, db.settings);
  
  res.json({
    username: user.username,
    password: user.password,
    serverHost: db.settings.serverHost,
    serverPort: db.settings.serverPort,
    deepLink,
    clientConfig
  });
});

// 9. GET Download TOML file
app.get('/api/users/:username/toml', (req, res) => {
  const db = readDB();
  const username = req.params.username;
  
  const user = db.users.find(u => u.username.toLowerCase() === username.toLowerCase());
  if (!user) {
    return res.status(404).json({ success: false, error: "User not found." });
  }
  
  const clientConfig = generateClientTOML(user, db.settings);
  
  res.setHeader('Content-disposition', `attachment; filename=trusttunnel_${username}.toml`);
  res.setHeader('Content-type', 'text/plain');
  res.charset = 'UTF-8';
  res.write(clientConfig);
  res.end();
});

// 10. POST Manual Service Restart (for settings page testing)
app.post('/api/system/restart', (req, res) => {
  const db = readDB();
  triggerRestart(db.settings, (err, output) => {
    if (err) {
      return res.status(500).json({ success: false, error: err.message, log: output });
    }
    res.json({ success: true, log: output });
  });
});

// 11. GET Check Service Status
app.get('/api/system/status', (req, res) => {
  const db = readDB();
  const cmd = db.settings.restartCommand || "";
  let serviceName = "trusttunnel";
  
  // Try to parse the service name from systemctl if configured that way
  if (cmd.includes("systemctl")) {
    const match = cmd.match(/systemctl\s+(?:restart|reload)\s+([a-zA-Z0-9_\-\.]+)/);
    if (match && match[1]) {
      serviceName = match[1];
    }
  }

  // Run a quick status check
  // On non-Linux or without systemctl, it will fail gracefully and we report a simulated active status
  exec(`systemctl is-active ${serviceName}`, (err, stdout, stderr) => {
    const statusStr = (stdout || "").trim();
    if (err) {
      // If error but it returned inactive/failed
      if (statusStr === "inactive" || statusStr === "failed") {
        return res.json({ status: statusStr, online: false });
      }
      // If execution error (e.g. windows local dev or systemctl not present)
      return res.json({ status: "simulated-online", online: true, note: "Command systemctl not found, running panel in stand-alone mode." });
    }
    
    const isOnline = statusStr === "active";
    res.json({ status: statusStr, online: isOnline });
  });
});

// Start Express App
app.listen(PORT, () => {
  console.log(`-----------------------------------------------`);
  console.log(` TrustTunnel Web Panel Server is running!`);
  console.log(` Access URL: http://localhost:${PORT}`);
  console.log(` Mode: Development & Production`);
  console.log(`-----------------------------------------------`);
});
